version: '3'

services:

  golang-application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-database

  postgres-database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${DBNAME}
    ports:
      - "8000:8000"
